### ISSUE TITLE
Unable to start train

### ISSUE THREAD

**Issue by bravma** [GustavZ/yolo_for_tf_od_api#2]
Hi
I replaced all the files mentioned and compiled the .proto files.
Now when I'm trying start the training process using train.py I get the following error:

`Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/git/bda/fridge/fridge/tf_objectdetection_api/object_detection/trainer.py", line 247, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/git/bda/fridge/fridge/tf_objectdetection_api/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/git/bda/fridge/fridge/tf_objectdetection_api/object_detection/trainer.py", line 164, in _create_losses
    resized_image, true_image_shape = detection_model.preprocess(image)
  File "/git/bda/fridge/fridge/tf_objectdetection_api/object_detection/meta_architectures/ssd_meta_arch.py", line 262, in preprocess
    dtype=[tf.float32, tf.int32])
  File "/git/bda/fridge/fridge/tf_objectdetection_api/object_detection/utils/shape_utils.py", line 201, in static_or_dynamic_map_fn
    outputs = [fn(arg) for arg in tf.unstack(elems)]
  File "/git/bda/fridge/fridge/tf_objectdetection_api/object_detection/utils/shape_utils.py", line 201, in <listcomp>
    outputs = [fn(arg) for arg in tf.unstack(elems)]
TypeError: batch_multiclass_non_max_suppression() missing 1 required positional argument: 'scores'
`
Do you have any ideas what could be wrong?

**Comment by rky0930** [comment]
Sorry for late reply. 
I think the error occurred at a line i didn't change. 
I guess non-max-suppression_fn couldn't get the score info. 
I don't know why ..  May i check your code and config file ?
